Return-Path: <dccp-owner@vger.kernel.org>
X-Original-To: lists+dccp@lfdr.de
Delivered-To: lists+dccp@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id 1AB836DEDE9
	for <lists+dccp@lfdr.de>; Wed, 12 Apr 2023 10:37:51 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S230366AbjDLIht (ORCPT <rfc822;lists+dccp@lfdr.de>);
        Wed, 12 Apr 2023 04:37:49 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:46446 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S230184AbjDLIh3 (ORCPT <rfc822;dccp@vger.kernel.org>);
        Wed, 12 Apr 2023 04:37:29 -0400
Received: from mail-io1-f70.google.com (mail-io1-f70.google.com [209.85.166.70])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id 3C0B3769D
        for <dccp@vger.kernel.org>; Wed, 12 Apr 2023 01:36:03 -0700 (PDT)
Received: by mail-io1-f70.google.com with SMTP id i68-20020a6b3b47000000b00760a6d1a015so998965ioa.1
        for <dccp@vger.kernel.org>; Wed, 12 Apr 2023 01:36:03 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20210112; t=1681288501; x=1683880501;
        h=to:from:subject:message-id:date:mime-version:x-gm-message-state
         :from:to:cc:subject:date:message-id:reply-to;
        bh=rN5LL/mhX9dYZOvabcHjv0kZZdZ2NjEFEF7pBMtQmz8=;
        b=ZtNz6/4OeDKgyiZAdr9ONhW6u55lYtftttIErjjx4cXi65pNLk+QHHgydNTQiCNgWr
         B5XQwZiDt1nTXLiWrwUDrsymtRgjdPIedBED7keXOXjaLkRipPdCtHOdYNPZR8dPnCrp
         nERm4yxQIgP/Pb9eQYYUbcc8h77MGOM5zmsTf6OB3v+aHYtYZN1bq1Yn6wOW0CRDg8C6
         yyWOj6nLUfSaU9V+YgOnsGxBhPdp0BLwBTE6i3LyS4//EZQ7wxXjuMChydPimYgJotm3
         wykrySHaIyX6RPcjUjYZdlDNfPLf2zs/tnWpLEXHJVJCWxXxgmjaHuPZZDSqfYh4AfjH
         KV4w==
X-Gm-Message-State: AAQBX9dPUsC4CpFG3FMJ2LwrnU17kQjdDP67SRcVIeA0O/d+fF/Yw+Ba
        NsDILXBxKVVdTUITHk3a06oIFV7XAu958V+8yrLJLNnHSACShJg=
X-Google-Smtp-Source: AKy350YIfhBATaCsSAx1MTdSfIX493BB+ipp0VwIn2GkJGJJZn/6Ktn8mynki0Lzd0xhwYT/J/q/eSEp+/FhJzcRfVgCuVDxwG5x
MIME-Version: 1.0
X-Received: by 2002:a02:85ea:0:b0:3c5:1971:1b7f with SMTP id
 d97-20020a0285ea000000b003c519711b7fmr5306205jai.6.1681288500882; Wed, 12 Apr
 2023 01:35:00 -0700 (PDT)
Date:   Wed, 12 Apr 2023 01:35:00 -0700
X-Google-Appengine-App-Id: s~syzkaller
X-Google-Appengine-App-Id-Alias: syzkaller
Message-ID: <000000000000dc33db05f91f7b42@google.com>
Subject: [syzbot] Monthly dccp report
From:   syzbot <syzbot+listd740d6f828e66494271a@syzkaller.appspotmail.com>
To:     dccp@vger.kernel.org, linux-kernel@vger.kernel.org,
        netdev@vger.kernel.org, syzkaller-bugs@googlegroups.com
Content-Type: text/plain; charset="UTF-8"
X-Spam-Status: No, score=-1.6 required=5.0 tests=BAYES_00,FROM_LOCAL_HEX,
        HEADER_FROM_DIFFERENT_DOMAINS,RCVD_IN_DNSWL_NONE,RCVD_IN_MSPIKE_H2,
        SPF_HELO_NONE,SPF_PASS,URIBL_BLOCKED autolearn=no autolearn_force=no
        version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <dccp.vger.kernel.org>
X-Mailing-List: dccp@vger.kernel.org

Hello dccp maintainers/developers,

This is a 30-day syzbot report for the dccp subsystem.
All related reports/information can be found at:
https://syzkaller.appspot.com/upstream/s/dccp

During the period, 0 new issues were detected and 0 were fixed.
In total, 6 issues are still open and 4 have been fixed so far.

Some of the still happening issues:

Crashes Repro Title
101     Yes   KASAN: use-after-free Read in ccid2_hc_tx_packet_recv
              https://syzkaller.appspot.com/bug?extid=554ccde221001ab5479a
43      Yes   BUG: "hc->tx_t_ipi == NUM" holds (exception!) at net/dccp/ccids/ccid3.c:LINE/ccid3_update_send_interval()
              https://syzkaller.appspot.com/bug?extid=94641ba6c1d768b1e35e
4       Yes   BUG: stored value of X_recv is zero at net/dccp/ccids/ccid3.c:LINE/ccid3_first_li() (3)
              https://syzkaller.appspot.com/bug?extid=2ad8ef335371014d4dc7

---
This report is generated by a bot. It may contain errors.
See https://goo.gl/tpsmEJ for more information about syzbot.
syzbot engineers can be reached at syzkaller@googlegroups.com.
