Return-Path: <dccp+bounces-17-lists+dccp=lfdr.de@vger.kernel.org>
X-Original-To: lists+dccp@lfdr.de
Delivered-To: lists+dccp@lfdr.de
Received: from ny.mirrors.kernel.org (ny.mirrors.kernel.org [IPv6:2604:1380:45d1:ec00::1])
	by mail.lfdr.de (Postfix) with ESMTPS id 53CF97E3538
	for <lists+dccp@lfdr.de>; Tue,  7 Nov 2023 07:31:35 +0100 (CET)
Received: from smtp.subspace.kernel.org (wormhole.subspace.kernel.org [52.25.139.140])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by ny.mirrors.kernel.org (Postfix) with ESMTPS id 8166D1C20938
	for <lists+dccp@lfdr.de>; Tue,  7 Nov 2023 06:31:34 +0000 (UTC)
Received: from localhost.localdomain (localhost.localdomain [127.0.0.1])
	by smtp.subspace.kernel.org (Postfix) with ESMTP id E487AB64C
	for <lists+dccp@lfdr.de>; Tue,  7 Nov 2023 06:31:33 +0000 (UTC)
Authentication-Results: smtp.subspace.kernel.org; dkim=none
X-Original-To: dccp@vger.kernel.org
Received: from lindbergh.monkeyblade.net (lindbergh.monkeyblade.net [23.128.96.19])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by smtp.subspace.kernel.org (Postfix) with ESMTPS id AEAD417C7
	for <dccp@vger.kernel.org>; Tue,  7 Nov 2023 04:52:24 +0000 (UTC)
Received: from mail-ot1-f69.google.com (mail-ot1-f69.google.com [209.85.210.69])
	by lindbergh.monkeyblade.net (Postfix) with ESMTPS id 97E89FE
	for <dccp@vger.kernel.org>; Mon,  6 Nov 2023 20:52:23 -0800 (PST)
Received: by mail-ot1-f69.google.com with SMTP id 46e09a7af769-6ce37195375so6894540a34.0
        for <dccp@vger.kernel.org>; Mon, 06 Nov 2023 20:52:23 -0800 (PST)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20230601; t=1699332741; x=1699937541;
        h=to:from:subject:message-id:date:mime-version:x-gm-message-state
         :from:to:cc:subject:date:message-id:reply-to;
        bh=nAp6NrkzveDLTFcK/QBlyXampAT5bnoWcodW9DteIEY=;
        b=s+vV6z0hLw5XJ+Ygz2hoUbfvtQPL0mDirIVb04S5YVCGqeUAonX2ncMU3hJUSTTIXN
         Sb8eULpQVbeSXm840iD07SSdMdAbbOR9jeW1GT2f2gLnYu2kMeApu/FElrIFhfIaJhkh
         bq6BusTDhtPqNwJnlAEiRGvIax5gKv/ehdJLXaG9tabytWMsE6MQAeGy9ZeuyiLimibw
         80Tst4HfD6JxDoC/iVBTvhDo4S3D5UNE6MPSZy3GSxTlHjSgwPuvJVpDbWzCCi11nXoW
         HXXkLb6C5IpWkHKKhSC+htRY1NCuyfN4QuYSjlT2IOWWus/NegseKZKNSr4yuJsc1PIY
         DN8w==
X-Gm-Message-State: AOJu0Yy0QBLIepT4NqjXGsq3YWfaSyQXLRQht3eXymFSZ2N6NM31cODu
	Wun7DiinK1jRNDuOxVHqSdVdMW62gYXI0XXp+n2WeBtTmnXwu2M=
X-Google-Smtp-Source: AGHT+IFF27op/Kwmmbi3biZNw7HPBJKNkjRdM+sIHsqhwmEFp3rYvx1gTgztLCdObmJvkS/O2IcmmDN+HGs/YgX5sOuJQS0Rr5qt
Precedence: bulk
X-Mailing-List: dccp@vger.kernel.org
List-Id: <dccp.vger.kernel.org>
List-Subscribe: <mailto:dccp+subscribe@vger.kernel.org>
List-Unsubscribe: <mailto:dccp+unsubscribe@vger.kernel.org>
MIME-Version: 1.0
X-Received: by 2002:a05:6808:128a:b0:3ae:5aab:a6f3 with SMTP id
 a10-20020a056808128a00b003ae5aaba6f3mr11617841oiw.5.1699332741146; Mon, 06
 Nov 2023 20:52:21 -0800 (PST)
Date: Mon, 06 Nov 2023 20:52:21 -0800
X-Google-Appengine-App-Id: s~syzkaller
X-Google-Appengine-App-Id-Alias: syzkaller
Message-ID: <000000000000642e40060988bc45@google.com>
Subject: [syzbot] Monthly dccp report (Nov 2023)
From: syzbot <syzbot+listc2ee659ad54baf9fc752@syzkaller.appspotmail.com>
To: dccp@vger.kernel.org, linux-kernel@vger.kernel.org, netdev@vger.kernel.org, 
	syzkaller-bugs@googlegroups.com
Content-Type: text/plain; charset="UTF-8"

Hello dccp maintainers/developers,

This is a 31-day syzbot report for the dccp subsystem.
All related reports/information can be found at:
https://syzkaller.appspot.com/upstream/s/dccp

During the period, 1 new issues were detected and 0 were fixed.
In total, 5 issues are still open and 6 have been fixed so far.

Some of the still happening issues:

Ref Crashes Repro Title
<1> 102     Yes   KASAN: use-after-free Read in ccid2_hc_tx_packet_recv
                  https://syzkaller.appspot.com/bug?extid=554ccde221001ab5479a
<2> 50      Yes   BUG: "hc->tx_t_ipi == NUM" holds (exception!) at net/dccp/ccids/ccid3.c:LINE/ccid3_update_send_interval()
                  https://syzkaller.appspot.com/bug?extid=94641ba6c1d768b1e35e
<3> 13      Yes   BUG: stored value of X_recv is zero at net/dccp/ccids/ccid3.c:LINE/ccid3_first_li() (3)
                  https://syzkaller.appspot.com/bug?extid=2ad8ef335371014d4dc7

---
This report is generated by a bot. It may contain errors.
See https://goo.gl/tpsmEJ for more information about syzbot.
syzbot engineers can be reached at syzkaller@googlegroups.com.

To disable reminders for individual bugs, reply with the following command:
#syz set <Ref> no-reminders

To change bug's subsystems, reply with:
#syz set <Ref> subsystems: new-subsystem

You may send multiple commands in a single email message.

