Return-Path: <dccp-owner@vger.kernel.org>
X-Original-To: lists+dccp@lfdr.de
Delivered-To: lists+dccp@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id 9F7427015ED
	for <lists+dccp@lfdr.de>; Sat, 13 May 2023 11:53:48 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S238477AbjEMJxq (ORCPT <rfc822;lists+dccp@lfdr.de>);
        Sat, 13 May 2023 05:53:46 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:46370 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S238406AbjEMJxp (ORCPT <rfc822;dccp@vger.kernel.org>);
        Sat, 13 May 2023 05:53:45 -0400
Received: from mail-io1-f70.google.com (mail-io1-f70.google.com [209.85.166.70])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id CD39149D8
        for <dccp@vger.kernel.org>; Sat, 13 May 2023 02:53:43 -0700 (PDT)
Received: by mail-io1-f70.google.com with SMTP id ca18e2360f4ac-76c6c1b16d2so627765339f.1
        for <dccp@vger.kernel.org>; Sat, 13 May 2023 02:53:43 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20221208; t=1683971623; x=1686563623;
        h=to:from:subject:message-id:date:mime-version:x-gm-message-state
         :from:to:cc:subject:date:message-id:reply-to;
        bh=XpTDZQjcGxi+ajlHN492tpRKsJXznBAYgs5Yl0gFw1A=;
        b=Hm8uvfurH2Ds91nI8k2hH7V1CbiDL09CgABNNJM6lkeFp/pdFaGPYmq99bkxiOUwEf
         KLbIghldJwJgw9Of4TFnJxAWYq6tXsEq5cPmPa0wXLar/vbQykoG8jbKCCGYtgXSFsTQ
         zmmB73uM5yyAi4xZMz4HR/SkvSZjeSlvUcXYbmS5S/921NeO7iMTQkkC0LbAPZ6es+N2
         4+uHm/giKjuZFgh9/QF7XnTNXwXD7ya5/9oA4KljdIjUmumMfZf5lCvAy7r4Ca9rU5Kw
         fYc8GSBk5xRijeSGIcgZhN5nv1VQa9kjde7IsbWZEPp++XJ2BB2t0qABm9vvL+1ixfGQ
         vB1w==
X-Gm-Message-State: AC+VfDw6qSnrRXK0k+pCsGshO8AgUwH0svzdCgzRZKdaZ6hUsxuUoaRR
        iwSHNFwMngpFVzo7LLLsehDRxg2uaj3M0SVMt4wGMaQ4nsu+8qk=
X-Google-Smtp-Source: ACHHUZ543xzX4eBQ6FCYcd3WkHPUfr9JU60LkafgjLtsJGUt9cSVlFK1QjxAkCiJOYVKAAUYpClcClJPYqDv+ylHIfdVhSUe0WVC
MIME-Version: 1.0
X-Received: by 2002:a5e:a910:0:b0:76c:6635:321d with SMTP id
 c16-20020a5ea910000000b0076c6635321dmr6194794iod.4.1683971623223; Sat, 13 May
 2023 02:53:43 -0700 (PDT)
Date:   Sat, 13 May 2023 02:53:43 -0700
X-Google-Appengine-App-Id: s~syzkaller
X-Google-Appengine-App-Id-Alias: syzkaller
Message-ID: <0000000000006a0c0805fb903235@google.com>
Subject: [syzbot] Monthly dccp report (May 2023)
From:   syzbot <syzbot+list3a2f3026c22f761712a0@syzkaller.appspotmail.com>
To:     dccp@vger.kernel.org, linux-kernel@vger.kernel.org,
        netdev@vger.kernel.org, syzkaller-bugs@googlegroups.com
Content-Type: text/plain; charset="UTF-8"
X-Spam-Status: No, score=-1.7 required=5.0 tests=BAYES_00,FROM_LOCAL_HEX,
        HEADER_FROM_DIFFERENT_DOMAINS,RCVD_IN_DNSWL_NONE,RCVD_IN_MSPIKE_H2,
        SPF_HELO_NONE,SPF_PASS,T_SCC_BODY_TEXT_LINE,URIBL_BLOCKED autolearn=no
        autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <dccp.vger.kernel.org>
X-Mailing-List: dccp@vger.kernel.org

Hello dccp maintainers/developers,

This is a 31-day syzbot report for the dccp subsystem.
All related reports/information can be found at:
https://syzkaller.appspot.com/upstream/s/dccp

During the period, 0 new issues were detected and 0 were fixed.
In total, 5 issues are still open and 4 have been fixed so far.

Some of the still happening issues:

Ref Crashes Repro Title
<1> 102     Yes   KASAN: use-after-free Read in ccid2_hc_tx_packet_recv
                  https://syzkaller.appspot.com/bug?extid=554ccde221001ab5479a
<2> 43      Yes   BUG: "hc->tx_t_ipi == NUM" holds (exception!) at net/dccp/ccids/ccid3.c:LINE/ccid3_update_send_interval()
                  https://syzkaller.appspot.com/bug?extid=94641ba6c1d768b1e35e
<3> 4       Yes   BUG: stored value of X_recv is zero at net/dccp/ccids/ccid3.c:LINE/ccid3_first_li() (3)
                  https://syzkaller.appspot.com/bug?extid=2ad8ef335371014d4dc7

---
This report is generated by a bot. It may contain errors.
See https://goo.gl/tpsmEJ for more information about syzbot.
syzbot engineers can be reached at syzkaller@googlegroups.com.

To disable reminders for individual bugs, reply with the following command:
#syz set <Ref> no-reminders

To change bug's subsystems, reply with:
#syz set <Ref> subsystems: new-subsystem

You may send multiple commands in a single email message.
